### ISSUE TITLE
Juwan issues <3

### ISSUE THREAD

**Issue by jnpoJuwan** [pontaoski/linja-insa#1]
since you asked me to post them here, here I shall post them.

* ala is the multiplication mark, it should take a taller shape
* the loops on esun are a bit too wide
* jaki has a very non-jaki shape
* jo may be too small, especially the lower half
* kasi looks interesting, I like it, tho maybe put the leafs higher on the stem
* ken is the Latin letter K
* kili is too fat, it should overall be smaller and also have a dent at the top
* kon is backwards isn't it? also please exaggerate the curves a bit more. same for linja and teo
* kule could be a bit wider
* la is too tall and too thin
* lawa could be a bit thinner, if it's a perfect circle then it makes it hard to read for me
* the top radical for loje/moku is too disproportionally big 
* lukin has to be squashed, not a perfect circle
* the top circle of mama could be bigger
* mani and moli don't match, one is a perfect circle one is a 
* meli/mije/tonsi could have the circles made bigger
** tonsi could also be the transgender symbol, to match sp more closely → ⚧️ 
* mun could be wider
* nanpa should be square
* nasa isn't curvy enough ;(
* noka could be wider overall
* kepeken/pali/pana, that thumb is too big!!
* palisa could be a bit more square, right now it's a perfect oval
* the chevrons on pan are too wide
* pini's top and bottom are bit too thin
* this isn't obligatory, but something fun I've seen, pipi could be thinner comparatively to akesi, see nasin Koko and linja lipamanka 
* sama could be wider
* seli is too short
* the bumps on sewi are too mathetically precise, if you get what I mean
* sijelo is an umbrella
* ~~the dots on sitelen are ovals, maybe try a down-up-down pattern?~~ not sure this is even a problem at all
* sona is a square instead of a rectangle
* soweli is too square
* the eyes on suwi are too tall 
* tan is pointing down, where it should be pointing back
* for toki, try fitting it into a square rather than a rectangle
* unpa is too thin, the negative space is too small
* the tops of the legs on utala are too long
* wan lacks the serif, hard to read
* weka, like ala, is too tiny
* the terminators on wile end a bit abruptly
* the chevrons on e are too packed together
* pilin is too mathematically precise
* lon is too small overall

I do want to say that you are doing a great job btw!!! it is your first work but it is way more than I could ever do

**Comment by sowelipililimute** [comment]
issues opened
